import type { Product } from "./types";

const APPAREL = ["XS", "S", "M", "L", "XL", "2XL"];
const JACKET = ["S", "M", "L", "XL", "2XL"];
const SUIT = ["46", "48", "50", "52", "54", "56"];

export const SEED_PRODUCTS: Product[] = [
  // ───────────────────────── LEATHER JACKETS ─────────────────────────
  {
    id: "lj-spiked-rebel",
    slug: "spiked-rebel-studded-jacket",
    name: "Spiked Rebel Studded Jacket",
    category: "leather-jackets",
    price: 349.99,
    compareAt: 429.99,
    description:
      "A full-grain biker statement piece — twin rows of blood-red conical studs running shoulder to cuff, claw-slash back graphic and the embroidered ‘Spiked’ wordmark. This is armour for the city.",
    details: [
      "Premium full-grain cowhide shell",
      "Hand-set anodised red spike studs",
      "Embroidered back graphic & wordmark",
      "Asymmetric YKK zip with storm flap",
      "Quilted viscose lining",
    ],
    images: ["/products/spiked-rebel.jpeg"],
    sizes: JACKET,
    colors: ["Black / Red"],
    badge: "Icon",
    featured: true,
    stock: 18,
  },
  {
    id: "lj-crimson-edge",
    slug: "crimson-edge-cafe-racer",
    name: "Crimson Edge Café Racer",
    category: "leather-jackets",
    price: 279.99,
    description:
      "Stand-collar café racer in jet-black lambskin with crimson padded shoulders and contrast zip piping. Slim, ribbed and built to move on the bike.",
    details: [
      "Soft napa lambskin",
      "Ribbed padded shoulders for abrasion zones",
      "Snap stand collar",
      "Two zip chest pockets, two hand pockets",
      "Red contrast piping throughout",
    ],
    images: [
      "/products/crimson-edge-1.jpeg",
      "/products/crimson-edge-3.jpeg",
      "/products/crimson-edge-3.png",
    ],
    sizes: JACKET,
    colors: ["Black / Crimson"],
    badge: "Bestseller",
    featured: true,
    stock: 24,
  },
  {
    id: "lj-rebel-classic",
    slug: "rebel-classic-biker",
    name: "Rebel Classic Biker",
    category: "leather-jackets",
    price: 259.99,
    description:
      "The timeless asymmetric-zip motorcycle jacket. Wide lapels, belted hem, mirror-polished hardware. The one every wardrobe is missing.",
    details: [
      "Heavyweight cowhide",
      "Asymmetric zip & snap-down lapels",
      "Adjustable waist belt",
      "Zip cuffs & dual chest pockets",
      "Smooth twill lining",
    ],
    images: [
      "/products/rebel-classic-front.jpeg",
      "/products/rebel-classic-back.png",
      "/products/rebel-classic-pair.jpeg",
    ],
    sizes: JACKET,
    colors: ["Black"],
    featured: true,
    stock: 30,
  },
  {
    id: "lj-noir-belted",
    slug: "noir-belted-biker",
    name: "Noir Belted Biker",
    category: "leather-jackets",
    price: 269.99,
    description:
      "A minimalist take on the Brando — pure matte-black leather, polished silver zips, clean belted waist. Quiet luxury with an edge.",
    details: [
      "Full-grain leather, matte finish",
      "Notch lapel with throat latch",
      "Buckled waist belt",
      "Four-pocket front",
      "Branded satin lining",
    ],
    images: ["/products/noir-belted.jpeg"],
    sizes: JACKET,
    colors: ["Black"],
    stock: 21,
  },
  {
    id: "lj-crimson-rebel",
    slug: "crimson-rebel-biker",
    name: "Crimson Rebel Biker",
    category: "leather-jackets",
    price: 289.99,
    description:
      "Classic double-rider silhouette traced in oxblood-red accent lines along the shoulders, cuffs and belt. Black core, red veins.",
    details: [
      "Cowhide shell with red leather inlays",
      "Quilted shoulder & elbow panels",
      "Asymmetric zip, belted hem",
      "Antique nickel hardware",
    ],
    images: ["/products/crimson-rebel.jpeg"],
    sizes: JACKET,
    colors: ["Black / Oxblood"],
    badge: "New",
    stock: 16,
  },
  {
    id: "lj-midnight-asym",
    slug: "midnight-asymmetric-moto",
    name: "Midnight Asymmetric Moto",
    category: "leather-jackets",
    price: 239.99,
    description:
      "Slouchy lapel collar, diagonal zip and a lived-in drape. The everyday leather that only looks better worn-in.",
    details: [
      "Supple sheepskin",
      "Lapel collar with stud tab",
      "Multiple zip pockets",
      "Relaxed rider fit",
    ],
    images: ["/products/midnight-asym.jpeg"],
    sizes: JACKET,
    colors: ["Black"],
    stock: 27,
  },
  {
    id: "lj-vintage-brown",
    slug: "vintage-brown-rider",
    name: "Vintage Brown Rider",
    category: "leather-jackets",
    price: 249.99,
    description:
      "Distressed tobacco-brown café racer with a hand-rubbed patina. Snap stand collar, twin chest zips, pure heritage.",
    details: [
      "Distressed waxed cowhide",
      "Snap band collar",
      "Vintage-finish brass zips",
      "Tailored slim fit",
    ],
    images: ["/products/vintage-brown.png"],
    sizes: JACKET,
    colors: ["Tobacco Brown"],
    badge: "Bestseller",
    stock: 19,
  },
  {
    id: "lj-tobacco-twotone",
    slug: "tobacco-two-tone-cafe-racer",
    name: "Tobacco Two-Tone Café Racer",
    category: "leather-jackets",
    price: 264.99,
    description:
      "Brown body, black sleeves and yoke — a two-tone racer with quilted shoulders and a snap stand collar. Equal parts retro and rugged.",
    details: [
      "Two-tone full-grain leather",
      "Quilted shoulder panels",
      "Twin zip chest pockets",
      "Snap band collar",
    ],
    images: ["/products/tobacco-twotone.jpeg"],
    sizes: JACKET,
    colors: ["Brown / Black"],
    stock: 22,
  },
  {
    id: "lj-emerald-quilted",
    slug: "emerald-quilted-biker",
    name: "Emerald Quilted Biker",
    category: "leather-jackets",
    price: 274.99,
    description:
      "Make a statement in deep teal-green. Ribbed quilted sleeves, double front zips and a diamond-quilted lining. Nothing else on the road like it.",
    details: [
      "Dyed teal lambskin",
      "Ribbed quilted sleeves",
      "Double asymmetric zips",
      "Diamond-quilted lining",
    ],
    images: ["/products/emerald-quilted.jpeg"],
    sizes: JACKET,
    colors: ["Emerald"],
    badge: "New",
    stock: 12,
  },
  {
    id: "lj-ivory-scarlet",
    slug: "ivory-scarlet-biker",
    name: "Ivory Scarlet Biker",
    category: "leather-jackets",
    price: 254.99,
    description:
      "Off-white shell with scarlet sleeve and shoulder panels. A bold, clean racer cut for those who don’t do all-black.",
    details: [
      "Ivory & scarlet leather panels",
      "Stand collar with strap",
      "Three zip chest pockets",
      "Slim athletic fit",
    ],
    images: ["/products/ivory-scarlet.png"],
    sizes: JACKET,
    colors: ["Ivory / Scarlet"],
    stock: 14,
  },
  {
    id: "lj-hornet-moto",
    slug: "hornet-moto-jacket",
    name: "Hornet Moto Jacket",
    category: "leather-jackets",
    price: 244.99,
    description:
      "High-vis hornet-yellow body with black-and-white racing flashes and a fleece-lined collar. Loud, warm and unmistakable.",
    details: [
      "Yellow / black colour-block leather",
      "Fleece-lined stand collar",
      "Diagonal main zip",
      "Zip side pockets",
    ],
    images: ["/products/hornet-moto.png"],
    sizes: JACKET,
    colors: ["Hornet Yellow"],
    stock: 17,
  },
  {
    id: "lj-dof-racer",
    slug: "dof-street-racer-jacket",
    name: "DOF Street Racer Jacket",
    category: "leather-jackets",
    price: 234.99,
    description:
      "Stand-collar street racer with diagonal red-and-cream banners and ‘DOF’ appliqué. Motorsport energy for the pavement.",
    details: [
      "Black PU racer shell",
      "Diagonal contrast banners",
      "Stand collar",
      "Zip chest & hand pockets",
    ],
    images: ["/products/dof-racer.jpeg"],
    sizes: JACKET,
    colors: ["Black / Red"],
    stock: 26,
  },
  {
    id: "lj-velocity-stripe",
    slug: "velocity-twin-stripe-jacket",
    name: "Velocity Twin-Stripe Jacket",
    category: "leather-jackets",
    price: 259.99,
    description:
      "Race-inspired black leather split by twin ivory stripes front and back, with ribbed shoulders and a belted hem. Pure speed iconography.",
    details: [
      "Full-grain leather",
      "Twin centre racing stripes",
      "Ribbed quilted shoulders",
      "Belted waist",
    ],
    images: ["/products/velocity-stripe.jpeg"],
    sizes: JACKET,
    colors: ["Black / Ivory"],
    badge: "New",
    stock: 15,
  },
  {
    id: "lj-apex-diamond",
    slug: "apex-diamond-racer",
    name: "Apex Diamond Racer",
    category: "leather-jackets",
    price: 269.99,
    description:
      "Geometric red, white and black diamond panels carve an aggressive silhouette. A track-jacket cut with full street attitude.",
    details: [
      "Tri-colour diamond panelling",
      "Ribbed side stretch panels",
      "Centre-zip stand collar",
      "Athletic moto fit",
    ],
    images: ["/products/apex-diamond.jpeg"],
    sizes: JACKET,
    colors: ["Red / White / Black"],
    stock: 13,
  },
  {
    id: "lj-motor-heritage",
    slug: "motor-heritage-jacket",
    name: "Motor Heritage Jacket",
    category: "leather-jackets",
    price: 229.99,
    description:
      "Vertical red-white-black racing stripes and a bold ‘MOTOR’ chest print. Banded collar and sleeve flashes complete the vintage rally look.",
    details: [
      "Striped PU leather shell",
      "Banded stand collar",
      "Sleeve racing flashes",
      "Zip front & side pockets",
    ],
    images: ["/products/motor-heritage.jpeg"],
    sizes: JACKET,
    colors: ["Black / Red / White"],
    stock: 20,
  },
  {
    id: "lj-monochrome-panel",
    slug: "monochrome-panel-biker",
    name: "Monochrome Panel Biker",
    category: "leather-jackets",
    price: 239.99,
    description:
      "Clean black-and-white panelled biker with ribbed shoulders, twin chest zips and a buckled stand collar. Sharp, balanced, timeless.",
    details: [
      "Black / white panel leather",
      "Buckled stand collar",
      "Ribbed shoulder & cuff detail",
      "Twin chest zip pockets",
    ],
    images: ["/products/monochrome-panel.jpeg"],
    sizes: JACKET,
    colors: ["Black / White"],
    stock: 23,
  },
  {
    id: "lj-phantom-stripe",
    slug: "phantom-stripe-racer",
    name: "Phantom Stripe Racer",
    category: "leather-jackets",
    price: 284.99,
    description:
      "Gloss-black racer with crisp white centre stripes, ribbed shoulders and a belted hem. Monochrome menace.",
    details: [
      "Glossy full-grain leather",
      "Twin white centre stripes",
      "Ribbed padded shoulders",
      "Belted hem, zip cuffs",
    ],
    images: ["/products/phantom-stripe.png"],
    sizes: JACKET,
    colors: ["Black / White"],
    stock: 11,
  },

  // ───────────────────────── RACING SUITS ─────────────────────────
  {
    id: "rs-apex-pro",
    slug: "apex-pro-one-piece-suit",
    name: "Apex Pro One-Piece Suit",
    category: "racing-suits",
    price: 899.99,
    compareAt: 1049.99,
    description:
      "Track-grade one-piece in white, blue and red with CE armour, external knee sliders and a stretch accordion back. Built for the apex.",
    details: [
      "1.2–1.4mm cowhide with stretch panels",
      "CE-rated shoulder, elbow & knee armour",
      "Replaceable magnesium knee sliders",
      "Aerodynamic speed hump",
      "Pre-curved race posture",
    ],
    images: ["/products/apex-pro-suit.jpeg"],
    sizes: SUIT,
    colors: ["White / Blue / Red"],
    badge: "Pro",
    featured: true,
    stock: 8,
  },
  {
    id: "rs-hivis-pro",
    slug: "hi-vis-pro-race-suit",
    name: "Hi-Vis Pro Race Suit",
    category: "racing-suits",
    price: 869.99,
    description:
      "Black-and-fluoro one-piece engineered for maximum track visibility. Perforated chest, titanium sliders and a sculpted aero hump.",
    details: [
      "Perforated competition cowhide",
      "Fluoro hi-vis accents",
      "Titanium external sliders",
      "Aero speed hump",
      "Full CE armour kit",
    ],
    images: ["/products/hivis-pro-suit.jpeg"],
    sizes: SUIT,
    colors: ["Black / Fluoro"],
    badge: "Pro",
    stock: 7,
  },
  {
    id: "rs-pearl-pro",
    slug: "pearl-pro-race-suit",
    name: "Pearl Pro Race Suit",
    category: "racing-suits",
    price: 879.99,
    description:
      "A clean pearl-white one-piece with perforated torso and aggressive pre-curved posture. Race-ready elegance.",
    details: [
      "Perforated kangaroo-grade leather",
      "Pre-curved race fit",
      "External knee & elbow sliders",
      "Stretch accordion panels",
    ],
    images: ["/products/pearl-pro-suit.jpeg", "/products/pearl-pro-alt.jpeg"],
    sizes: SUIT,
    colors: ["Pearl White"],
    stock: 6,
  },
  {
    id: "rs-tricolore",
    slug: "tricolore-two-piece-suit",
    name: "Tricolore Two-Piece Suit",
    category: "racing-suits",
    price: 749.99,
    description:
      "Zip-together two-piece in white, blue and red with sculpted leg armour. Track performance with everyday off-bike comfort.",
    details: [
      "Jacket + trouser zip-together suit",
      "Tricolour leather panels",
      "CE knee & shoulder armour",
      "Full 360° connection zip",
    ],
    images: ["/products/tricolore-suit.jpeg"],
    sizes: SUIT,
    colors: ["White / Blue / Red"],
    stock: 9,
  },
  {
    id: "rs-venom-green",
    slug: "venom-green-two-piece-suit",
    name: "Venom Green Two-Piece Suit",
    category: "racing-suits",
    price: 729.99,
    description:
      "White and black two-piece sliced through with venom-green flashes. Knee armour, stretch panels and a zip-together waist.",
    details: [
      "Two-piece zip-together leathers",
      "Venom-green accent lines",
      "Hard knee & shoulder armour",
      "Stretch lumbar panel",
    ],
    images: ["/products/venom-green-suit.jpeg"],
    sizes: SUIT,
    colors: ["White / Green"],
    badge: "New",
    stock: 10,
  },
  {
    id: "rs-rosa-pro",
    slug: "rosa-pro-womens-suit",
    name: "Rosa Pro Women’s Suit",
    category: "racing-suits",
    price: 819.99,
    description:
      "Women’s one-piece in black with magenta and white accents, contoured for a female race fit. Full armour, external sliders, aero hump.",
    details: [
      "Women’s contoured race cut",
      "Magenta & white accents",
      "CE armour throughout",
      "External knee sliders",
    ],
    images: ["/products/rosa-pro-suit.jpeg"],
    sizes: SUIT,
    colors: ["Black / Magenta"],
    badge: "Women’s",
    featured: true,
    stock: 7,
  },
  {
    id: "rs-rosa-twopiece",
    slug: "rosa-two-piece-womens-suit",
    name: "Rosa Two-Piece Women’s Suit",
    category: "racing-suits",
    price: 699.99,
    description:
      "Women’s zip-together two-piece in white, black and pink. Track-grade protection that moves with you on and off the bike.",
    details: [
      "Women’s two-piece zip-together",
      "Pink / white / black panels",
      "Knee & shoulder armour",
      "Stretch comfort panels",
    ],
    images: ["/products/rosa-twopiece-suit.jpeg"],
    sizes: SUIT,
    colors: ["White / Pink / Black"],
    badge: "Women’s",
    stock: 8,
  },

  // ───────────────────────── RASHGUARDS ─────────────────────────
  {
    id: "rg-gear5",
    slug: "gear-5-awakening-rashguard",
    name: "Gear 5 Awakening Rashguard",
    category: "rashguards",
    price: 44.99,
    description:
      "Short-sleeve compression rashguard drenched in monochrome smoke-cloud sublimation. Four-way stretch, flatlock seams, second-skin fit.",
    details: [
      "88% polyester / 12% spandex",
      "Full-print sublimation (won’t crack or peel)",
      "Flatlock stitching for zero chafe",
      "Moisture-wicking & quick-dry",
      "Anti-microbial finish",
    ],
    images: ["/products/gear5-front.jpeg", "/products/gear5-back.jpeg"],
    sizes: APPAREL,
    colors: ["Black / White"],
    badge: "Bestseller",
    featured: true,
    stock: 60,
  },
  {
    id: "rg-symbiote",
    slug: "symbiote-strike-rashguard",
    name: "Symbiote Strike Rashguard",
    category: "rashguards",
    price: 44.99,
    description:
      "Short-sleeve grappling rashguard with a full-body symbiote print and side mesh ventilation. Engineered to grip the mats, not your skin.",
    details: [
      "Compression poly-spandex blend",
      "Full wrap-around sublimation",
      "Side ventilation panels",
      "Flatlock seams",
      "IBJJF-legal cut",
    ],
    images: ["/products/symbiote-rg-front.png", "/products/symbiote-rg-back.jpeg"],
    sizes: APPAREL,
    colors: ["Black"],
    featured: true,
    stock: 48,
  },
  {
    id: "rg-neon-wolf",
    slug: "neon-predator-long-sleeve-rashguard",
    name: "Neon Predator Long-Sleeve Rashguard",
    category: "rashguards",
    price: 49.99,
    description:
      "Long-sleeve rashguard in black with electric-lime fracture print and a snarling triple-wolf chest graphic. Warmth, coverage and venom.",
    details: [
      "Long-sleeve compression fit",
      "Electric-lime fracture sublimation",
      "Flatlock stitching",
      "Quick-dry, anti-microbial",
    ],
    images: ["/products/neon-wolf-front.jpeg", "/products/neon-wolf-back.jpeg"],
    sizes: APPAREL,
    colors: ["Black / Lime"],
    badge: "New",
    stock: 40,
  },
  {
    id: "rg-forest-wolf",
    slug: "forest-alpha-rashguard",
    name: "Forest Alpha Rashguard",
    category: "rashguards",
    price: 44.99,
    description:
      "Teal forest-scape sublimation with a circular alpha-wolf crest. Short sleeve, breathable, built for the roll.",
    details: [
      "Poly-spandex compression",
      "Teal forest full-print",
      "Flatlock seams",
      "Moisture-wicking",
    ],
    images: ["/products/forest-wolf-front.jpeg"],
    sizes: APPAREL,
    colors: ["Teal"],
    stock: 36,
  },
  {
    id: "rg-primal-bear",
    slug: "primal-roar-rashguard",
    name: "Primal Roar Rashguard",
    category: "rashguards",
    price: 44.99,
    description:
      "A roaring red-muscled bear bursts across a deep-teal forest backdrop. Short-sleeve compression with second-skin stretch.",
    details: [
      "Compression poly-spandex",
      "High-detail bear sublimation",
      "Flatlock stitching",
      "Quick-dry finish",
    ],
    images: ["/products/primal-bear-back.png"],
    sizes: APPAREL,
    colors: ["Teal"],
    stock: 34,
  },
  {
    id: "rg-imperial-dragon",
    slug: "imperial-dragon-rashguard",
    name: "Imperial Dragon Rashguard",
    category: "rashguards",
    price: 46.99,
    description:
      "Dark camo body with a cobalt centre stripe and a coiled silver dragon. Short-sleeve compression with serious presence.",
    details: [
      "Dark camo + cobalt sublimation",
      "Silver dragon back graphic",
      "Compression fit",
      "Flatlock seams",
    ],
    images: ["/products/imperial-dragon-back.jpeg"],
    sizes: APPAREL,
    colors: ["Camo / Cobalt"],
    badge: "New",
    stock: 30,
  },
  {
    id: "rg-molten",
    slug: "molten-core-rashguard",
    name: "Molten Core Rashguard",
    category: "rashguards",
    price: 44.99,
    description:
      "Cracked-lava print glowing orange over black. Short-sleeve compression that runs as hot as your training.",
    details: [
      "Molten-lava full sublimation",
      "Compression poly-spandex",
      "Flatlock stitching",
      "Moisture-wicking",
    ],
    images: ["/products/molten-front.jpeg", "/products/molten-back.jpeg"],
    sizes: APPAREL,
    colors: ["Black / Orange"],
    stock: 38,
  },
  {
    id: "rg-midnight-camo",
    slug: "midnight-camo-rashguard",
    name: "Midnight Camo Rashguard",
    category: "rashguards",
    price: 42.99,
    description:
      "Stealthy black camo with a single cobalt chest band. The clean, understated rashguard for everyday rolls.",
    details: [
      "Black camo sublimation",
      "Cobalt chest band",
      "Compression fit",
      "Flatlock seams",
    ],
    images: ["/products/midnight-camo-front.jpeg"],
    sizes: APPAREL,
    colors: ["Black Camo"],
    stock: 44,
  },

  // ───────────────────────── FIGHT SHORTS ─────────────────────────
  {
    id: "fs-symbiote",
    slug: "symbiote-fight-shorts",
    name: "Symbiote Fight Shorts",
    category: "fight-shorts",
    price: 39.99,
    description:
      "Hybrid grappling shorts with a full symbiote print, deep side split and a hook-and-loop locking waistband. Move without limits.",
    details: [
      "4-way stretch micro-fibre shell",
      "Full-print sublimation",
      "Hook-and-loop + drawcord waist",
      "Deep side splits for mobility",
      "Bonded, no-rub seams",
    ],
    images: [
      "/products/symbiote-shorts-front.jpeg",
      "/products/symbiote-shorts-back.jpeg",
    ],
    sizes: APPAREL,
    colors: ["Black"],
    featured: true,
    stock: 52,
  },
];
